SELECT COUNT(*) FROM production.products
WITH T1 (PRODUCT_ID) 
AS 
(
    SELECT product_id FROM sales.order_items GROUP BY product_id
) 
SELECT COUNT(*) FROM T1

SELECT T1.PRODUCT_ID, PRODUCT_NAME, ORDER_ID 
FROM PRODUCTION.PRODUCTS T1
LEFT JOIN SALES.ORDER_ITEMS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE ORDER_ID IS NULL
ORDER BY T1.PRODUCT_ID


SELECT T1.PRODUCT_ID, PRODUCT_NAME, ORDER_ID 
FROM SALES.ORDER_ITEMS T2
RIGHT JOIN PRODUCTION.PRODUCTS T1
ON T1.PRODUCT_ID = T2.PRODUCT_ID
--WHERE ORDER_ID IS NULL
ORDER BY T1.PRODUCT_ID

SELECT T1.PRODUCT_ID, PRODUCT_NAME, ORDER_ID 
FROM PRODUCTION.PRODUCTS T1
FULL JOIN SALES.ORDER_ITEMS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE ORDER_ID IS NULL
ORDER BY T1.PRODUCT_ID


SELECT T1.STAFF_ID, (T1.FIRST_NAME + ' ' + T1.LAST_NAME) AS FULL_NAME, 
T1.MANAGER_ID, T2.FIRST_NAME AS MANAGER_NAME 
FROM SALES.STAFFS AS T1
LEFT JOIN SALES.STAFFS AS T2
ON T1.MANAGER_ID = T2.STAFF_ID