USE EXAMPLE1
GO

SELECT * FROM PRODUCTION.PRODUCTS
SELECT ORDER_ID, ITEM_ID, T1.PRODUCT_ID, QUANTITY, T2.PRODUCT_NAME,
T2.LIST_PRICE, DISCOUNT, 
(QUANTITY * T2.LIST_PRICE)-((QUANTITY * T2.LIST_PRICE)*DISCOUNT) AS TOTAL
FROM SALES.ORDER_ITEMS AS T1
JOIN PRODUCTION.PRODUCTS AS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID

SELECT ORDER_ID,  
SUM((QUANTITY * LIST_PRICE)-((QUANTITY * LIST_PRICE)*DISCOUNT)) AS TOTAL
FROM SALES.ORDER_ITEMS AS T1
GROUP BY ORDER_ID