/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasetest;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author j0z3ph
 */
public class Main extends javax.swing.JFrame {

    private final String DBURL
            = "jdbc:sqlserver://serveruri;"
            + "databaseName=BD;"
            + "encrypt=true;"
            + "trustServerCertificate=true;"
            + "user=USER;"
            + "password=PASSWORD;";

    //private final String DBURL = "jdbc:sqlserver://localhost;databaseName=prueba;integratedSecurity=true;encrypt=false;";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try {
            DriverManager.registerDriver(new com.microsoft.sqlserver.jdbc.SQLServerDriver());
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTest = new javax.swing.JTable();
        btnSelectBad = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSelectGood = new javax.swing.JButton();
        txtNuevoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdUpdate = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pruebas");

        btnListar.setLabel("Select");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tableTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableTest);

        btnSelectBad.setLabel("Select :C");
        btnSelectBad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBadActionPerformed(evt);
            }
        });

        txtId.setToolTipText("");

        jLabel1.setText("Customer ID");

        btnSelectGood.setText("Select :D");
        btnSelectGood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectGoodActionPerformed(evt);
            }
        });

        jLabel2.setText("Nuevo Nombre");

        jLabel3.setText("Customer ID");

        txtIdUpdate.setToolTipText("");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSP.setText("Agregar con SP");
        btnSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria");

        txtCategoria.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelectBad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelectGood, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCategoria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnSelectBad)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSelectGood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSP))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(
                    "SELECT store_id, store_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.stores;"
            );

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8});
            }

            this.tableTest.setModel(dtm);
            rs.close();
            state.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSelectBadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBadActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Apellido");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(
                    "SELECT customer_id, first_name, last_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.customers "
                    + "WHERE customer_id = " + this.txtId.getText()
            );

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                String str9 = rs.getString(9);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8, str9});
            }

            this.tableTest.setModel(dtm);
            rs.close();
            state.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectBadActionPerformed

    private void btnSelectGoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectGoodActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Apellido");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            PreparedStatement statement = con.prepareStatement(
                    "SELECT customer_id, first_name, last_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.customers "
                    + "WHERE customer_id = ?");
            //statement.setInt(1, Integer.parseInt(this.txtId.getText()));
            statement.setString(1, this.txtId.getText());

            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                String str9 = rs.getString(9);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8, str9});
            }

            this.tableTest.setModel(dtm);
            rs.close();
            statement.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelectGoodActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Connection con = DriverManager.getConnection(DBURL);
            PreparedStatement statement = con.prepareStatement(
                    "UPDATE sales.customers SET first_name = ? "
                    + "WHERE customer_id = ?");
            statement.setString(1, this.txtNuevoNombre.getText());
            statement.setString(2, this.txtIdUpdate.getText());

            int res = statement.executeUpdate();

            if (res == 0) {
                JOptionPane.showMessageDialog(this, "No se actualizo NADA",
                        "Update",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Se actualizaron "
                        + res + " registros.",
                        "Update",
                        JOptionPane.INFORMATION_MESSAGE);
            }
          
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPActionPerformed
        try {
            Connection con = DriverManager.getConnection(DBURL);
            CallableStatement statement = con.prepareCall(
                    "{CALL dbo.sp_add_category2(?,?)}"
            );
            statement.setString(1, this.txtCategoria.getText());
            statement.registerOutParameter(2, java.sql.Types.VARCHAR);

            statement.executeUpdate();

            JOptionPane.showMessageDialog(this, statement.getString(2),
                        "Insert",
                        JOptionPane.INFORMATION_MESSAGE);
            
            CallableStatement call = con.prepareCall(
                    "{CALL dbo.sp_get_categories()}"
            );
            
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Categoria");
            
            ResultSet rs = call.executeQuery();

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                dtm.addRow(new Object[]{str1, str2});
            }

            this.tableTest.setModel(dtm);
            rs.close();
            call.close();
            statement.close();
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSP;
    private javax.swing.JButton btnSelectBad;
    private javax.swing.JButton btnSelectGood;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTest;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdUpdate;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
